In [30]:
import numpy as np

In [34]:
x = np.random.random(size=(5, 5))
x_mean = np.mean(x)
x_var = np.var(x)
x_norm = (x - x_mean) / np.sqrt(x_var)


In [35]:
print(x_norm)

[[-1.20165659 -0.61972822 -0.56341019 -0.9684483   0.54895768]
 [ 0.90210031 -1.19958106  0.50073096  1.39678586 -1.28618505]
 [-0.53350268  1.76713508 -0.11834681 -0.50921408 -0.60226072]
 [ 1.70624494 -0.72537942 -1.46355101  1.56044943  0.43400779]
 [ 0.90717338 -0.76933421  0.99686837 -0.72758368  0.56772823]]
