In [1]:
import numpy as np

In [5]:
print(np.random.random((3,3,3)))

[[[0.60898225 0.58494413 0.03913407]
  [0.16261954 0.558954   0.89643474]
  [0.1246428  0.22756795 0.40028192]]

 [[0.06175902 0.30772572 0.24673956]
  [0.80919423 0.48878102 0.49303456]
  [0.56003486 0.51497672 0.44309823]]

 [[0.05387742 0.3707495  0.98952618]
  [0.16198462 0.01563652 0.78050092]
  [0.65387477 0.74141824 0.09767382]]]
