In [2]:
import numpy as np

In [4]:
a=np.random.random((5,5))

In [5]:
print(a)

[[0.8625204  0.39721589 0.55778035 0.23194421 0.16240298]
 [0.67270676 0.85407126 0.2249833  0.21992703 0.90508532]
 [0.91851038 0.69819443 0.9170482  0.92943296 0.88339764]
 [0.04801799 0.38458762 0.58623253 0.50807543 0.06568104]
 [0.65787648 0.50376786 0.62035873 0.20447235 0.33245417]]


In [14]:
print((np.diag([1,2,3,4,5])))

      


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
