In [1]:
import numpy as np

In [2]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 4. 2. 8. 1. 6. 8. 4. 1. 9.]
[1. 4. 2. 8. 1. 6. 8. 4. 1. 9.]
[1. 4. 2. 8. 1. 6. 8. 4. 1. 9.]
[1 4 2 8 1 6 8 4 1 9]
[1. 4. 2. 8. 1. 6. 8. 4. 1. 9.]
